/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package archivos;

/**
 *
 * @author Alejandro
 */
public class Menu2 extends javax.swing.JFrame {

    /**
     * Creates new form Menu2
     */
    public Menu2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_Crear = new javax.swing.JMenuItem();
        menu_Renombrar = new javax.swing.JMenuItem();
        menu_Borrar = new javax.swing.JMenuItem();
        menu_Copiar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout pantallaLayout = new javax.swing.GroupLayout(pantalla);
        pantalla.setLayout(pantallaLayout);
        pantallaLayout.setHorizontalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 678, Short.MAX_VALUE)
        );
        pantallaLayout.setVerticalGroup(
            pantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
        );

        jMenu1.setText("Administrar Archivos");

        menu_Crear.setText("Crear Archivo");
        menu_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CrearActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Crear);

        menu_Renombrar.setText("Renombrar Archivo");
        menu_Renombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_RenombrarActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Renombrar);

        menu_Borrar.setText("Borrar Archivo");
        menu_Borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_BorrarActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Borrar);

        menu_Copiar.setText("Copiar Archivo");
        menu_Copiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_CopiarActionPerformed(evt);
            }
        });
        jMenu1.add(menu_Copiar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pantalla)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CrearActionPerformed
        crearArchivo1 nuevo = new crearArchivo1();
        pantalla.add(nuevo);
        pantalla.setLocation(10, 10);
        nuevo.setVisible(true);
    }//GEN-LAST:event_menu_CrearActionPerformed

    private void menu_RenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_RenombrarActionPerformed
        renombrarArchivo renombrar = new renombrarArchivo();
        pantalla.add(renombrar);
        pantalla.setLocation(10, 10);
        renombrar.setVisible(true);
    }//GEN-LAST:event_menu_RenombrarActionPerformed

    private void menu_BorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_BorrarActionPerformed
        eliminarArchivo eliminar = new eliminarArchivo();
        pantalla.add(eliminar);
        pantalla.setLocation(10, 10);
        eliminar.setVisible(true);
    }//GEN-LAST:event_menu_BorrarActionPerformed

    private void menu_CopiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_CopiarActionPerformed
        copiarArchivo copiar = new copiarArchivo();
        pantalla.add(copiar);
        pantalla.setLocation(10, 10);
        copiar.setVisible(true);
    }//GEN-LAST:event_menu_CopiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menu_Borrar;
    private javax.swing.JMenuItem menu_Copiar;
    private javax.swing.JMenuItem menu_Crear;
    private javax.swing.JMenuItem menu_Renombrar;
    private javax.swing.JDesktopPane pantalla;
    // End of variables declaration//GEN-END:variables
}
