/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package framecliente;

import java.net.*;

/**
 * The class chatClientView implements the view for the chat client application.
 * It displays the basic GUI which will be used by the chat users. It also retrieves
 * the hostname and IPv4 address of the  host during start-up.
 * 
 * @author aorozco bigfito@gmail.com
 * @version 1.0
 */
public class framecliente extends javax.swing.JFrame {
    
    /**
     * A String to keep the hostname of the machine running the client.
     */
    String clientHostname;
    
    /**
     * A String to keep the IPv4 address of the machine running the client.
     */
    String clientIPAddress;

    /**
     * Creates new form clientWindow
     */
    public framecliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtServerAddress = new javax.swing.JTextField();
        txtServerPort = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHostName = new javax.swing.JLabel();
        lblIpAddress = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        btnCONNECT = new javax.swing.JButton();
        btnDISCONNECT = new javax.swing.JButton();
        lblUserStatus = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtChatArea = new javax.swing.JTextArea();
        txtChatMessage = new javax.swing.JTextField();
        btnSEND = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtUsersList = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotificationArea = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();

        txtServerAddress.setText("127.0.0.1");

        txtServerPort.setModel(new javax.swing.SpinnerNumberModel(32565, 0, 65535, 1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel8.setText("PORT");

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("STATUS");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jLabel4.setText("HOSTNAME");

        lblHostName.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblHostName.setText("LOCALHOST");

        lblIpAddress.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        lblIpAddress.setText("255.255.255.255");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jLabel6.setText("IP ADDRESS");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ventana de Clientes");
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(690, 70));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel1.setText("Estatus");

        btnCONNECT.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCONNECT.setText("CONECTAR");
        btnCONNECT.setName("btnCONNECT"); // NOI18N

        btnDISCONNECT.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDISCONNECT.setText("DESCONECTAR");
        btnDISCONNECT.setEnabled(false);
        btnDISCONNECT.setName("btnDISCONNECT"); // NOI18N

        lblUserStatus.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblUserStatus.setForeground(new java.awt.Color(204, 0, 204));
        lblUserStatus.setText("DESCONECTADO");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        jLabel3.setText("CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCONNECT, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDISCONNECT, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUserStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(259, 259, 259))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCONNECT)
                    .addComponent(btnDISCONNECT)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUserStatus))
                .addContainerGap())
        );

        txtChatArea.setEditable(false);
        txtChatArea.setColumns(20);
        txtChatArea.setRows(5);
        jScrollPane3.setViewportView(txtChatArea);

        txtChatMessage.setEditable(false);

        btnSEND.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnSEND.setText("ENVIAR");
        btnSEND.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("AREA Conexion");

        txtUsersList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(txtUsersList);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("USUARIOS ONLINE");

        txtNotificationArea.setEditable(false);
        txtNotificationArea.setColumns(20);
        txtNotificationArea.setRows(5);
        jScrollPane1.setViewportView(txtNotificationArea);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtChatMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSEND, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChatMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSEND)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The setLblHostName method sets a hostname for the hostname label on the GUI.
     * @param strText A String representing the hostname to set up.
     */
    public void setLblHostName(String strText) {
        this.lblHostName.setText(strText);
    }

    /**
     * The setLblIpAddress method sets an IP address for the IP address label on the GUI.
     * @param strText A String representing the IP address to set up.
     */
    public void setLblIpAddress(String strText) {
        this.lblIpAddress.setText(strText);
    }
    
    /**
     * The addTextToNotificationArea method adds text to the notification area in
     * the GUI.
     * @param strText A String representing the text to append.
     */
    public void addTextToNotificationArea(String strText){
        this.txtNotificationArea.append(strText + "\n");
    }
      
    /**
     * The getTextFromChatMessage method returns the text that has been input into
     * the chat message text field.
     * @return A String representing the text from the chat message field.
     */
    public String getTextFromChatMessage(){
        return txtChatMessage.getText();
    }
    
    /**
     * The setupNetworkFields method retrieves the hostname and IPv4 address of the
     * machine running the chat client in order to display the values on the GUI.
     */
    public void setupNetworkFields(){
        
        InetAddress hostMachine;        
        try{
            
            hostMachine = InetAddress.getLocalHost();
            clientIPAddress = hostMachine.getHostAddress();
            clientHostname = hostMachine.getHostName();

            lblHostName.setText( clientHostname );
            lblIpAddress.setText( clientIPAddress );
            
        }catch(UnknownHostException uhe){
            txtNotificationArea.append("[ERROR]: ERROR AL OBTENER LA INFORMACION DE RED DEL HOST.\n");
            txtNotificationArea.append( uhe.toString() + "\n" );
        }        
    }
    
    /**
     * The getClientHostname method returns the hostname of the machine running
     * the chat client.
     * @return A String representing the chat client's hostname.
     */
    public String getClientHostname(){
        return clientHostname;
    }
    
    /**
     * The getClientIPAddress method returns the IP address of the machine running
     * the chat client.
     * @return A String representing the chat client's IPv4 address.
     */
    public String getClientIPAddress(){
        return clientIPAddress;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCONNECT;
    private javax.swing.JButton btnDISCONNECT;
    private javax.swing.JButton btnSEND;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblHostName;
    private javax.swing.JLabel lblIpAddress;
    private javax.swing.JLabel lblUserStatus;
    private javax.swing.JTextArea txtChatArea;
    private javax.swing.JTextField txtChatMessage;
    private javax.swing.JTextArea txtNotificationArea;
    private javax.swing.JTextField txtServerAddress;
    private javax.swing.JSpinner txtServerPort;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JList<String> txtUsersList;
    // End of variables declaration//GEN-END:variables

    /**
     * The getButtonConnectReference method returns a reference of the CONNECT button
     * from the GUI.
     * @return A JButton reference of the CONNECT button from the GUI.
     */
    public javax.swing.JButton getButtonConnectReference(){
        return btnCONNECT;
    }
    
    /**
     * The getButtonDisconnectReference method returns a reference of the DISCONNECT button
     * from the GUI.
     * @return A JButton reference of the DISCONNECT button from the GUI.
     */
    public javax.swing.JButton getButtonDisconnectReference(){
        return btnDISCONNECT;
    }
    
    /**
     * The getButtonSendReference method returns a reference of the SEND button
     * from the GUI.
     * @return A JButton reference of the SEND button from the GUI.
     */
    public javax.swing.JButton getButtonSendReference(){
        return btnSEND;
    }
    
    /**
     * The getTxtServerAddress method returns a reference of the server address
     * text field from the GUI.
     * @return A JTextField reference of the IPv4 server address text field from the GUI.
     */
    public javax.swing.JTextField getTxtServerAddress(){
        return txtServerAddress;
    }    
    
    /**
     * The getTxtUserNameReference method returns a reference of the username
     * text field from the GUI.
     * @return A JTextField reference of the username text field from the GUI.
     */
    public javax.swing.JTextField getTxtUserNameReference(){
        return txtUserName;
    }

    /**
     * The getTxtChatMessageReference method returns a reference of the chat message
     * text field from the GUI.
     * @return A JTextField reference of the chat message text field from the GUI.
     */
    public javax.swing.JTextField getTxtChatMessageReference(){
        return txtChatMessage;
    }

    /**
     * The getTxtServerPort method returns a reference of the server port field
     * from the GUI.
     * @return A JSpinner reference of the server port field from the GUI.
     */
    public javax.swing.JSpinner getTxtServerPort(){
        return txtServerPort;
    }
    
    /**
     * The getTxtChatAreaReference method returns a reference of the chat area field
     * from the GUI.
     * @return A JTextArea reference of the chat area field from the GUI.
     */
    public javax.swing.JTextArea getTxtChatAreaReference(){
        return txtChatArea;
    }
    
    /**
     * The getTxtNotificationAreaReference method returns a reference of the chat
     * notification area field from the GUI.
     * @return A JTextArea reference of the chat notificaation area field from the GUI.
     */
    public javax.swing.JTextArea getTxtNotificationAreaReference(){
        return txtNotificationArea;
    }
    
    /**
     * The getTxtUsersListReference method returns a reference of the list of users
     * component from the GUI.
     * @return A JList reference of the list of users field from the GUI.
     */
    public javax.swing.JList<String> getTxtUsersListReference(){
        return txtUsersList;
    }    
    
    /**
     * The getLblUserStatus method returns a reference of the client's status
     * label from the GUI.
     * @return A JLabel reference of the client's status field from the GUI.
     */
    public javax.swing.JLabel getLblUserStatus(){
        return lblUserStatus;
    }
    
    /**
     * The getLblClientHostname method returns a reference of the client's hostname
     * label from the GUI.
     * @return A JLabel reference of the client's hostname label field from the GUI.
     */
    public javax.swing.JLabel getLblClientHostname(){
        return lblHostName;
    }
    
    /**
     * The getLblClientIPAddress method returns a reference of the client's IPv4
     * address label from the GUI.
     * @return A JLabel reference of the client's IPv4 label field from the GUI.
     */
    public javax.swing.JLabel getLblClientIPAddress(){
        return lblIpAddress;
    }    
}
